models/Angsuran.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "angsuran".
 *
 * @property int $id_angsuran
 * @property string $nama_user
 * @property string $tanggal
 * @property string $jumlah_angsuran
 */
class Angsuran extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'angsuran';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nama_user', 'tanggal', 'jumlah_angsuran'], 'required'],
            [['tanggal'], 'safe'],
            [['jumlah_angsuran'], 'string'],
            [['nama_user'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_angsuran' => 'Id Angsuran',
            'nama_user' => 'Nama User',
            'tanggal' => 'Tanggal',
            'jumlah_angsuran' => 'Jumlah Angsuran',
        ];
    }
}

controllers/AngsuranController.php
<?php
namespace app\controllers;

use app\models\Angsuran;
use app\models\Pinjam;
use yii\db\Command;
use Yii;

class AngsuranController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $dataPinjam = Yii::$app->db->createCommand("SELECT id_pinjam,nama_peminjam FROM pinjam")
        ->queryAll();
        
        return $this->render('index',['dataPinjam'=>$dataPinjam]);
    }
    public function actionCari()
    {
        $model=new Angsuran();
        if($model->load(Yii::$app->request->post(), '')){
            $id_pinjam=$_POST['Pegawai']['id_pinjam'];
            $dataPinjam = Yii::$app->db->createCommand("SELECT * FROM pinjam WHERE nama_peminjam='$id_pinjam'")
                        ->queryAll();
        return $this->render('index',['dataPinjam'=>$dataPinjam]);

        }
    }

}

views/angsuran/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
$this->title = 'Angsuran';
?>
<div class="container">
    <div class="col-md-6">
    <?php
        $form = ActiveForm::begin([
            'method' => 'post',
            'action' => Url::to(['angsuran/cari']),
        ]);
        ?>
        <table>
            <tr>
                <td>
                <select class="form-control" style="margin-right: 5px;" id="pegawai-id_jabatan" name="Pegawai[id_pinjam]">                        
                <?php
                    foreach($dataPinjam as $jbt){
                ?>
                    <option value= <?=$jbt['nama_peminjam']?>><?=$jbt['nama_peminjam']?></option>
                <?php
                    }
                ?>
            </select>
                </td>
                <td>
                <?= Html::submitButton('Submit', array('class' => 'btn btn-primary', 'style' => 'width:100%; border-radius:0px;')) ?>
                </td>
            </tr>
    </table>
    <?php
        ActiveForm::end();
    ?>
    </div>
    <?php
    if(isset($dataPinjam)){
        ?>
        <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col">Nama</th>
                <th scope="col">Jumlah</th>
                <th scope="col">Tanggal</th>
                <th scope="col">Jaminan</th>
                <th scope="col">No Seri Jaminan</th>
                </tr>
            </thead>
            <tbody>
            <?php
            foreach($dataPinjam as $row){
        ?>
            <tr>
                <td><?=$row['nama_peminjam']?></td>
                <td>Rp. <?= number_format($row['jumlah_pinjam'], 2, ',', '.')?> </td>
                <td><?=$row['tanggal']?></td>
                <td><?=$row['jaminan']?></td>
                <td><?=$row['no_seri_jaminan']?></td>                
            </tr>
            <?php
            }
        ?>
            </tbody>
            </table>
    <?php } ?>
</div>